### ISSUE TITLE
Read model support?

### ISSUE THREAD

**Issue by cjbakersciex** [nagytech/lagom-dotnet#1]
I noticed some of the sqlserver read model support is commented out.  Is it usable at this point?  If so, do you have an example of how to use it?

**Comment by nagytech** [comment]
@cjbakersciex Readmodel support does work, but I'm not happy with the way it turned out.  As of a few weeks ago I started re-writing the cluster startup so that the read-side was a bit easier to control.

If I can't get v2.0 stable in the next little while, I'll write up a sample on how to do it with v1

**Comment by cjbakersciex** [comment]
Ok, great.  Thanks @nagytech.

**Comment by nagytech** [comment]
@cjbakersciex The latest on master has an example of how the read side works.  

https://github.com/nagytech/lagom-dotnet/commit/017f5d7118b5e1e9047bb2ed1ff4c534df6061f0

Any questions let me know.

**Comment by cjbaker** [comment]
Thanks @nagytech.  Is there somewhere we can discuss your project directly?

**Comment by wwjn** [comment]
Email sent
